import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#32170d",
        "primary-container": "#4b2c20",
        "on-primary": "#ffffff",
        "on-primary-container": "#bf9282",
        "primary-fixed": "#ffdbce",
        "primary-fixed-dim": "#ecbcaa",
        "on-primary-fixed": "#2e140a",
        "on-primary-fixed-variant": "#613e31",
        secondary: "#5f5e58",
        "secondary-container": "#e5e2da",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#66645e",
        tertiary: "#002321",
        "tertiary-container": "#183936",
        "tertiary-fixed": "#c6eae5",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#81a39e",
        "on-tertiary-fixed": "#00201e",
        "on-tertiary-fixed-variant": "#2c4c49",
        surface: "#f4fafe",
        "surface-bright": "#f4fafe",
        "surface-dim": "#d4dbde",
        "surface-variant": "#dde3e7",
        "surface-container": "#e8eff2",
        "surface-container-low": "#eef5f8",
        "surface-container-high": "#e2e9ec",
        "surface-container-highest": "#dde3e7",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#161d1f",
        "on-surface-variant": "#504440",
        background: "#f4fafe",
        "on-background": "#161d1f",
        outline: "#83746f",
        "outline-variant": "#d5c3bd",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "inverse-primary": "#ecbcaa",
        "inverse-surface": "#2b3134",
        "surface-tint": "#7b5647",
      },
      fontFamily: {
        headline: ["var(--font-newsreader)", "serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
